import {useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,Volume2,Heart,ArrowUpRight,Disc3,Music2,Upload,Headphones,Plus,Guitar,Drum,Mic2,AudioLines} from 'lucide-react';
import {MultitrackEngine,type EngineSnapshot} from './audio/engine';
import {catalog} from './audio/catalog';
import {useYouTube} from './useYouTube';

type Mode='instrumental'|'studio'|'original'|'official';
const base=import.meta.env.BASE_URL;
const time=(n:number)=>`${Math.floor((n||0)/60)}:${String(Math.floor((n||0)%60)).padStart(2,'0')}`;
const blank:EngineSnapshot={duration:0,position:0,playing:false,tracks:[]};
const credits=[{name:'Acoustic guitars',artist:'Paul Simon · David Spinozza',icon:Guitar},{name:'Bass guitar',artist:'Russell George',icon:Music2},{name:'Percussion & cuíca',artist:'Airto Moreira',icon:Drum},{name:'Lead vocal',artist:'Paul Simon',icon:Mic2}];
export default function App(){
 const [mode,setMode]=useState<Mode>('studio');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [mix,setMix]=useState(blank);const [direct,setDirect]=useState({playing:false,position:0,duration:0});const [volume,setVolume]=useState(.85);const [local,setLocal]=useState(false);const [singing,setSinging]=useState(false);const [markers,setMarkers]=useState<number[]>([]);
 const transportRequest=useRef(0);const engine=useRef(new MultitrackEngine());const audio=useRef<HTMLAudioElement>(null);const yt=useYouTube(mode==='official');
 useEffect(()=>{const id=setInterval(()=>setMix(engine.current.getSnapshot()),100);return()=>{clearInterval(id);engine.current.dispose()}},[]);
 const state=mode==='official'?yt:mode==='studio'?mix:direct;
 function changeMode(next:Mode){++transportRequest.current;audio.current?.pause();engine.current.pause();if(mode==='official')yt.pause();setError('');setMarkers([]);setMode(next)}
 function readAudio(){const a=audio.current;if(a)setDirect({playing:!a.paused&&!a.ended,position:a.currentTime,duration:Number.isFinite(a.duration)?a.duration:0})}
 async function loadBand(){setBusy(true);setError('');try{const inputs=[];for(const t of catalog.tracks){const res=await fetch(base+t.url);if(!res.ok)throw new Error(`Could not load ${t.id}. Please check your connection and try again.`);inputs.push({id:t.id,file:new File([await res.blob()],t.id+'.mp3',{type:'audio/mpeg'})})}await engine.current.load(inputs,true);engine.current.setMute('Lead vocal',!singing);setLocal(false);setMix(engine.current.getSnapshot());}catch(e){setError(message(e));throw e}finally{setBusy(false)}}
 async function play(full=false){const request=++transportRequest.current;setError('');try{if(mode==='official'){if(!yt.ready){setError('The official player is still loading. You can also tap Play inside it.');return}if(full)yt.volume(volume);yt.play()}else if(mode==='studio'){await engine.current.unlock();if(request!==transportRequest.current)return;if(!engine.current.getSnapshot().tracks.length)await loadBand();if(request!==transportRequest.current)return;if(full){engine.current.fullBand();if(!local)engine.current.setMute('Lead vocal',!singing)}setMix(engine.current.getSnapshot());await engine.current.play();setMix(engine.current.getSnapshot())}else{if(audio.current){audio.current.volume=volume*(mode==='original'?.7150765755:.760339);await audio.current.play()}}}catch(e){setError(message(e))}}
 function pause(){++transportRequest.current;if(mode==='official')yt.pause();else if(mode==='studio')engine.current.pause();else audio.current?.pause()}
 function stop(){++transportRequest.current;if(mode==='official')yt.stop();else if(mode==='studio')engine.current.stop();else if(audio.current){audio.current.pause();audio.current.currentTime=0;readAudio()}}
 function seek(n:number){if(mode==='official')yt.seek(n);else if(mode==='studio')engine.current.seek(n);else if(audio.current){audio.current.currentTime=n;readAudio()}}
 async function importTracks(files:FileList|null){if(!files?.length)return;++transportRequest.current;setBusy(true);setError('');try{await engine.current.load(Array.from(files).map((file,i)=>({id:`${i+1}. ${file.name.replace(/\.[^.]+$/,'')}`,file})));setLocal(true);setMix(engine.current.getSnapshot())}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <div className="app"><header className="masthead"><a href="#home" className="brand"><Disc3 size={23}/><span>THE FAMILY BAND</span></a><span className="edition">A LITTLE RECORD. A LOT OF LOVE.</span><span className="gift"><Heart size={14}/> FOR MOM</span></header>
 <main id="home"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> THE MOM COLLECTION · VOL. 01</div><h1>Me & Julio<span>Down by the<br/>Schoolyard.</span></h1><p className="intro">Some songs feel like sunshine.<br/>This one will always sound like you.</p><p className="dedication">Made with love for Mom <span>♥</span></p><button className="full-play" onClick={()=>void play(true)} disabled={busy}><Play size={18} fill="currentColor"/>{busy?'LOADING THE BAND…':'PLAY FULL BAND'}</button></div>
 <div className="turntable"><div className="deck-label">FAMILY RECORDS <span>EST. WITH LOVE</span></div><div className={`vinyl ${state.playing?'spinning':''}`} data-testid="vinyl"><div className="record-ring"/><div className="portrait"><img src={base+'mom.png'} alt="Mom smiling, on her very own record label"/><span className="label-caption">MOM'S GREATEST HITS</span></div></div><div className="tonearm"><i/><b/></div><div className="deck-bottom"><span><i className={state.playing?'light on':'light'}/> {state.playing?'NOW SPINNING':'READY WHEN YOU ARE'}</span><span>33⅓ RPM</span></div></div></section>
 <section className="console" aria-label="Music player"><div className="mode-bar" role="group" aria-label="Choose recording"><button disabled={busy} aria-pressed={mode==='instrumental'} onClick={()=>changeMode('instrumental')}>The instrumental</button><button disabled={busy} aria-pressed={mode==='studio'} onClick={()=>changeMode('studio')}>Explore the band</button><button disabled={busy} aria-pressed={mode==='original'} onClick={()=>changeMode('original')}>Original recording <ArrowUpRight size={13}/></button></div>
 <div className="player-content"><div className="now-playing"><div className="mini-art"><Music2/></div><div><p className="eyebrow">{mode==='official'?'PAUL SIMON · OFFICIAL AUDIO':mode==='original'?'LICENSED FULL RECORDING':mode==='studio'?(local?'YOUR LOCAL SESSION':'LICENSED RECORDING · SEPARATED PARTS'):'YOUR FAMILY RECORD'}</p><h2>Me and Julio Down by the Schoolyard</h2><p className="source-note">{mode==='official'?'1972 studio recording · Plays through YouTube':mode==='original'?'Full source mix · Best recording fidelity':mode==='studio'?'Make your own mix. Solo a part, or bring everyone back in.':'The instrumental you shared, here with love.'}</p></div><span className="session-tag">{mode==='original'?'SIDE B':'SIDE A'}</span></div>
 <div className="transport"><button className="full-play" onClick={()=>void play(true)} disabled={busy}><AudioLines size={18}/>{busy?'LOADING…':'RESTORE FULL BAND'}</button><button className="round-button" aria-label={state.playing?'Pause':'Resume'} onClick={()=>state.playing?pause():void play()} disabled={busy}>{state.playing?<Pause size={20}/>:<Play size={20}/>}</button><button className="round-button" aria-label="Stop and restart" onClick={stop}><RotateCcw size={19}/></button><div className="transport-label"><span className={state.playing?'live-dot active':'live-dot'}/>{busy?'Preparing audio':state.playing?'Playing':state.position>0?'Paused':'Press play. Make a memory.'}</div>{mode!=='studio'&&<label className="master-volume"><Volume2 size={18}/><input aria-label="Master volume" type="range" min="0" max="1" step="0.01" value={volume} onChange={e=>{const n=Number(e.target.value);setVolume(n);if(audio.current)audio.current.volume=n*(mode==='original'?.7150765755:.760339);yt.volume(n)}}/></label>}</div>
 <div className="timeline"><span>{time(state.position)}</span><input type="range" aria-label="Song position" min="0" max={state.duration||1} step="0.1" value={Math.min(state.position,state.duration||1)} disabled={!state.duration} onChange={e=>seek(Number(e.target.value))} style={{'--progress':`${state.duration?state.position/state.duration*100:0}%`} as React.CSSProperties}/><span>{time(state.duration)}</span></div>
 {(error||(mode==='official'&&yt.error))&&<div className="error" role="alert">{error||yt.error}</div>}
 {mode==='official'&&<div className="official"><div id="official-player"/><p>This is the original finished mix. YouTube does not provide individual instrument controls. <a href="https://www.youtube.com/watch?v=JVdlpZ4M-Hw" target="_blank" rel="noreferrer">Open official audio <ArrowUpRight size={12}/></a></p></div>}
 {mode==='studio'&&<><div className="studio-note"><Headphones size={17}/><span>Real audio, separated from the licensed full recording. Some sounds may bleed between parts. These are estimates, not original studio stems.</span></div>{!local&&<button className={'singing-toggle '+(singing?'enabled':'')} disabled={busy} aria-pressed={singing} onClick={()=>{const next=!singing;setSinging(next);if(engine.current.getSnapshot().tracks.length)engine.current.setMute('Lead vocal',!next);setMix(engine.current.getSnapshot())}}><Mic2 size={17}/>{singing?'Singing is on':'Add singing'}<span>Paul Simon · same recording, same timeline</span></button>}{!mix.tracks.length?<button className="load-button" onClick={()=>void loadBand().catch(()=>{})} disabled={busy}><AudioLines size={18}/>{busy?'Preparing your session…':'Load the instrument parts'}</button>:<div className="tracks">{mix.tracks.map((t,i)=>{const Icon=i===3?Mic2:i===1?Music2:i===2?Drum:Guitar;return <article className={'track '+(t.active?'sounding':'')} key={t.id}><div className="track-top"><span className="track-number">0{i+1}</span><span className={'activity '+(t.active?'lit':'')} aria-label={t.active?'Playing':'Not playing'}/></div><Icon className="instrument-icon" size={36} strokeWidth={1.2}/><h3>{t.id}</h3><p>{local?'Local audio file':catalog.tracks[i]?.description}</p><div className="track-actions"><button aria-label={`Solo ${t.id}`} aria-pressed={t.solo} onClick={()=>{engine.current.setSolo(t.id,!engine.current.getSnapshot().tracks.find(x=>x.id===t.id)!.solo);setMix(engine.current.getSnapshot())}}>S <span>Solo</span></button><button aria-label={`Mute ${t.id}`} aria-pressed={t.mute} onClick={()=>{const muted=engine.current.getSnapshot().tracks.find(x=>x.id===t.id)!.mute;engine.current.setMute(t.id,!muted);if(t.id==='Lead vocal'&&!local)setSinging(muted);setMix(engine.current.getSnapshot())}}>M <span>Mute</span></button></div><label className="track-volume"><Volume2 size={14}/><input type="range" aria-label={`${t.id} volume`} min="0" max="1" step=".01" value={t.volume} onChange={e=>{engine.current.setVolume(t.id,Number(e.target.value));setMix(engine.current.getSnapshot())}}/><span>{Math.round(t.volume*100)}</span></label></article>})}</div>}
 <div className="session-tools">{local&&<button disabled={busy} onClick={()=>{++transportRequest.current;void loadBand().catch(()=>{})}}>Restore song session</button>}<button onClick={()=>{if(state.duration)setMarkers(m=>[...m,state.position])}} disabled={!state.duration||markers.length>=8}><Plus size={14}/>Bookmark this moment</button>{markers.map((m,i)=><button key={i} onClick={()=>seek(m)}>↺ {time(m)}</button>)}<label className="import-label"><Upload size={14}/>Your own stems<input aria-label="Import aligned audio tracks" disabled={busy} type="file" accept="audio/*,.mp4" multiple onChange={e=>{void importTracks(e.target.files);e.target.value=''}}/></label></div><p className="local-note">Local files stay on your device. Use aligned exports of equal length. Up to 12 tracks, 120 MB combined.</p></>}
 </div></section>
 <section className="liner-notes"><div className="section-heading"><div><p className="eyebrow">BEHIND THE RECORD</p><h2>A little band. An unforgettable groove.</h2></div><span>THE ORIGINAL 1972 LINEUP</span></div><div className="credits">{credits.map(c=><article key={c.name}><c.icon size={25} strokeWidth={1.3}/><h3>{c.name}</h3><p>{c.artist}</p></article>)}</div><p className="credits-note">Original-recording credits. The instrumental is a separately supplied file; it is not represented as Paul Simon's master.</p></section>
 <footer><span className="footer-logo"><Disc3 size={20}/> Me & Julio <i>|</i> The Family Band</span><span>For all the songs we share. <Heart size={13}/></span><details><summary>About the music & privacy</summary><p>The recordings were supplied by Josh under his stated licenses for this project. Public hosting and separated versions were confirmed on October 9, 2026. Instrument parts and vocal are machine-separated estimates from the same full recording, with possible bleed and artifacts. Two guitar players and cuíca cannot be reliably isolated individually. The full recording mode preserves the supplied mix for the closest available fidelity. The optional official player uses Paul Simon's YouTube upload, subject to YouTube availability. Opening it connects to YouTube. Local imports are never uploaded. This site has no analytics or account requirement.</p><button className='about-player' onClick={()=>changeMode('official')}>Open official YouTube player</button><a href="https://github.com/Hackk-cyte/me-and-julio-family-band/blob/main/docs/audio-reference.md" target="_blank" rel="noreferrer">Audio sources & credits <ArrowUpRight size={12}/></a></details></footer>
 <audio ref={audio} src={base+(mode==='original'?'audio/original-mix.mp3':catalog.instrumental)} preload="metadata" onTimeUpdate={readAudio} onLoadedMetadata={()=>{if(audio.current)audio.current.volume=volume*(mode==='original'?.7150765755:.760339);readAudio()}} onPlay={readAudio} onPause={readAudio} onEnded={readAudio} onError={()=>setError('The instrumental could not load. Check your connection and try Play again, or choose Original recording.')}/>
 </main></div>
}
function message(e:unknown){return e instanceof Error?e.message:'Audio could not start. Please try again.'}






